# See more config options at https://github.com/gakonst/foundry/tree/master/config
# The "default" profile will be used if none is specified
# The "ci" profile inherits from it, with modifications for use in CI

[profile.default]
# forge config
verbosity = 3
# solidity config
solc-version = "0.8.15"
optimizer = true
optimizer-runs = 1
remappings = ["test/=test/", "script/=script/"] # Allows imports using e.g. `test/` to refer to root `test` directory.

# Verbosity levels (https://onbjerg.github.io/foundry-book/forge/tests.html#logs-and-traces)
#   Level 2 (-vv): Logs emitted during tests are also displayed.
#   Level 3 (-vvv): Stack traces for failing tests are also displayed.
#   Level 4 (-vvvv): Stack traces for all tests are displayed, and setup traces for failing tests are displayed.
#   Level 5 (-vvvvv): Stack traces and setup traces are always displayed.

[profile.ci.fuzz]
runs = 1000